# Generated by Django 3.2.7 on 2021-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='아이디')),
                ('passwd', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('student_id', models.CharField(max_length=10, verbose_name='학번')),
                ('department', models.CharField(choices=[('경영학', '경영학'), ('화학과', '화학과'), ('전자공학과', '전자공학과'), ('컴퓨터공학과', '컴퓨터공학과'), ('사회학과', '사회학과'), ('회화과', '회화과'), ('무용과', '무용과'), ('체육교육과', '체육교육과'), ('법학과', '법학과')], max_length=50, verbose_name='학과')),
                ('grade', models.CharField(choices=[('선택안함', '선택안함'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년', '4학년'), ('졸업생', '졸업생')], max_length=20, verbose_name='학년')),
                ('level', models.CharField(choices=[('3', 'LV3_미인증사용자'), ('2', 'LV2_인증사용자'), ('1', 'LV1_관리자'), ('0', 'LV0_개발자')], max_length=30, verbose_name='등급')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
        ),
    ]
